# Constants for the process video
STEPSIZE = 5
FRAME_LIMIT = 20
DOWNSCALE_FACTOR = 2

# Constants for the compute transform
RANSAC_ITER = 5000
RANSAC_THRESHOLD = 0.01
DISTANCE = 50

# Good values
# STEPSIZE = 5
# FRAME_LIMIT = 100
# DOWNSCALE_FACTOR = 2

# RANSAC_ITER = 5000
# RANSAC_THRESHOLD = 0.01
# DISTANCE = 50

# DEBUG CONTROL
DEBUG = False